### ISSUE TITLE
ASCII85 filter bug

### ISSUE THREAD

**Issue by alex-tchernov** [tecnickcom/tc-lib-pdf-filter#3]
if stream ends with '<\~>' there is a bug in processing
https://github.com/tecnickcom/tc-lib-pdf-filter/blob/develop/src/Type/AsciiEightFive.php
line 50
 if (strpos($data, '<\~') !== false) {
 shoud be
 if (strpos($data, '<~') === 0) {

**Comment by nicolaasuni** [comment]
I have update the code in the release 1.14.15.
The provided input is invalid and the code throws and exception as expected.
The current version now removes any character before the starting sequence '<~'.

**Comment by alex-tchernov** [comment]
Sorry, but I don't believe that issue is closed.

As far as I read specification PDF format doesn't use "<~" as a start marker (PDF 32000-1:2008 7.4.3)
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf
May be it is used in some implenations or other veersion - I don't know.

But symbol "<" is PERMITTED in ASCII85. 
So the ASCII85 stream may be something like "abcd<~>" 
Where "abcd<" represents encoded data and last two symbols - eod marker.

**Comment by nicolaasuni** [comment]
I will investigate this a bot more...

**Comment by nicolaasuni** [comment]
Indeed the docs do not mention any start sequence, so I remove it.
I have added some additional tests.
Note the sequence '<~>' is still invalid because there is only one input character '<'.

**Comment by alex-tchernov** [comment]
Thanks

PS
"if stream ENDS with '<~>' ..."
